import ValuedFieldTheory.LocalField.Unramified.BaseChange
import ValuedFieldTheory.LocalField.Unramified.BaseChangeCore
import ValuedFieldTheory.LocalField.Unramified.BasicInvariants
import ValuedFieldTheory.LocalField.Unramified.Composition
import ValuedFieldTheory.LocalField.Unramified.Definitions
import ValuedFieldTheory.LocalField.Unramified.FiniteSupport
import ValuedFieldTheory.LocalField.Unramified.HenselReduction
import ValuedFieldTheory.LocalField.Unramified.HenselianAlgebraicExtension
import ValuedFieldTheory.LocalField.Unramified.MaximalResidue
import ValuedFieldTheory.LocalField.Unramified.MaximalSubextension
import ValuedFieldTheory.LocalField.Unramified.RamificationIndexTower
import ValuedFieldTheory.LocalField.Unramified.ResidueEmbedding
import ValuedFieldTheory.LocalField.Unramified.ResidueLifting
import ValuedFieldTheory.LocalField.Unramified.Separable

set_option autoImplicit false
