import ClassFieldTheory.AlgebraicNumberTheory.Completion.UnramifiedComparison.CompletionToIdeal
import ClassFieldTheory.AlgebraicNumberTheory.Completion.UnramifiedComparison.IdealToCompletion
import ClassFieldTheory.AlgebraicNumberTheory.Completion.UnramifiedComparison.LocalNorm
import ClassFieldTheory.AlgebraicNumberTheory.Completion.UnramifiedComparison.RamificationIndex

set_option autoImplicit false

/-! # Unramified comparisons between completions and prime ideals -/
