name = "ClassFieldTheory"
version = "2.0.0"
defaultTargets = ["ClassFieldTheory.All"]
enableArtifactCache = false
restoreAllArtifacts = false

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "5ed2965256430c3649e86755f9576b54eca72435"

[[lean_lib]]
name = "ClassFieldTheory.All"
srcDir = "Lean4"
globs = ["ClassFieldTheory.+"]
leanOptions = {linter.missingDocs = true}

[[lean_lib]]
name = "ValuedFieldTheory"
srcDir = "Lean4"
globs = ["ValuedFieldTheory.+"]

[[lean_lib]]
name = "GaloisCohomology"
srcDir = "Lean4"
globs = ["GaloisCohomology.+"]

[[lean_lib]]
name = "ProCGroups"
srcDir = "Lean4"
globs = ["ProCGroups.+"]
