import ValuedFieldTheory.Ramification.Herbrand.Average
import ValuedFieldTheory.Ramification.Herbrand.FixedField
import ValuedFieldTheory.Ramification.Herbrand.Function
import ValuedFieldTheory.Ramification.Herbrand.Quotient
import ValuedFieldTheory.Ramification.Herbrand.Tower

set_option autoImplicit false
