import ClassFieldTheory.AlgebraicNumberTheory.NumberField.CompletelySplitPrimes
import ClassFieldTheory.AlgebraicNumberTheory.NumberField.CompletelySplitPrimesModFour
import ClassFieldTheory.AlgebraicNumberTheory.NumberField.DegreeOnePrimes
import ClassFieldTheory.AlgebraicNumberTheory.NumberField.IntegralPrimitiveElement
import ClassFieldTheory.AlgebraicNumberTheory.NumberField.SchurPrimeDivisors
import ClassFieldTheory.AlgebraicNumberTheory.NumberField.EverywhereUnramifiedTower
import ClassFieldTheory.AlgebraicNumberTheory.NumberField.FiniteUnramifiedEtaleBridge
import ClassFieldTheory.AlgebraicNumberTheory.NumberField.FiniteUnramifiedTower
import ClassFieldTheory.AlgebraicNumberTheory.NumberField.CompletelySplitFinset
import ClassFieldTheory.AlgebraicNumberTheory.NumberField.GaloisDifferentBound
import ClassFieldTheory.AlgebraicNumberTheory.NumberField.RootDiscriminantBound
import ClassFieldTheory.AlgebraicNumberTheory.NumberField.SupportedDiscriminantBound
import ClassFieldTheory.AlgebraicNumberTheory.NumberField.TameDifferentTrace

set_option autoImplicit false

/-! # Finite and everywhere-unramified towers of number fields -/
