import ValuedFieldTheory.Ramification.GaloisValuation.AbsoluteGalois.All
import ValuedFieldTheory.Ramification.GaloisValuation.ClosedFixingSubgroup
import ValuedFieldTheory.Ramification.GaloisValuation.CompositumRestriction
import ValuedFieldTheory.Ramification.GaloisValuation.IntermediateFieldRestriction
import ValuedFieldTheory.Ramification.GaloisValuation.Ramification
import ValuedFieldTheory.Ramification.GaloisValuation.RamificationQuotients

set_option autoImplicit false
