import LocalClassFieldTheory.Concrete.ClassFormation.CohomologyBridge
import LocalClassFieldTheory.Concrete.ClassFormation.FieldUnitsHerbrand
import LocalClassFieldTheory.Concrete.ClassFormation.FilteredLiftingSequence
import LocalClassFieldTheory.Concrete.ClassFormation.Hilbert90
import LocalClassFieldTheory.Concrete.ClassFormation.IntegerUnitsHerbrand
import LocalClassFieldTheory.Concrete.ClassFormation.Main
import LocalClassFieldTheory.Concrete.ClassFormation.NormalBasis
import LocalClassFieldTheory.Concrete.ClassFormation.NormalBasisCohomology
import LocalClassFieldTheory.Concrete.ClassFormation.NormalBasisFiniteQuotient
import LocalClassFieldTheory.Concrete.ClassFormation.NormalBasisGaloisAction
import LocalClassFieldTheory.Concrete.ClassFormation.NormalBasisGradedLifting
import LocalClassFieldTheory.Concrete.ClassFormation.NormalBasisInfiniteProduct
import LocalClassFieldTheory.Concrete.ClassFormation.NormalBasisRecursiveLifting
import LocalClassFieldTheory.Concrete.ClassFormation.PrincipalUnitGraded
import LocalClassFieldTheory.Concrete.ClassFormation.Valuation
import LocalClassFieldTheory.Concrete.ClassFormation.ValuationHerbrand
import LocalClassFieldTheory.Concrete.ClassFormation.ValueGroupCohomology
import LocalClassFieldTheory.Concrete.ClassFormation.ArchimedeanNormQuotient
import LocalClassFieldTheory.Concrete.ClassFormation.LocalBlocks
import LocalClassFieldTheory.Concrete.ClassFormation.LocalizedCompletionCohomology
import LocalClassFieldTheory.Concrete.ClassFormation.ArchimedeanHilbert90

/-!
# The local class formation

Public aggregate for the normal-basis, unit-filtration, valuation, and
cohomology calculations establishing the local class-field axiom.
-/
