import LocalClassFieldTheory.Concrete.Infinite.ProfiniteCompletion
import LocalClassFieldTheory.Concrete.Infinite.AbstractProfiniteCompletionComparison
import LocalClassFieldTheory.Concrete.Infinite.LocalMultiplicativeCompletion
import LocalClassFieldTheory.Concrete.Infinite.ProfiniteCompletionCriteria
import LocalClassFieldTheory.Concrete.Infinite.TopologicalAbelianizationCongr
import LocalClassFieldTheory.Concrete.Infinite.AbsoluteGaloisAbelianization
import LocalClassFieldTheory.Concrete.Infinite.AbsoluteFiniteQuotients
import LocalClassFieldTheory.Concrete.Infinite.AbsoluteFiniteQuotientTransitions
import LocalClassFieldTheory.Concrete.Infinite.AbsoluteArtin
import LocalClassFieldTheory.Concrete.Infinite.FiniteAbelianQuotientKernels
import LocalClassFieldTheory.Concrete.Infinite.ProfiniteLocalReciprocity
import LocalClassFieldTheory.Concrete.Infinite.FiniteReciprocityDiagram

/-!
# Infinite local class field theory

Public aggregate for the topological profinite completion, compatible finite
Artin maps, the absolute local Artin map, and the profinite local reciprocity
equivalence.
-/
