import LubinTate
import LocalClassFieldTheory.Concrete.LubinTateApplication.NormIndex
import LocalClassFieldTheory.Concrete.LubinTateApplication.NormSubgroup
import LocalClassFieldTheory.Concrete.LubinTateApplication.LubinTateTransport
import LocalClassFieldTheory.Concrete.LubinTateApplication.LaurentPrincipalUnitTransport
import LocalClassFieldTheory.Concrete.LubinTateApplication.EqualCharacteristicTransportedUpperRamification
import LocalClassFieldTheory.Concrete.LubinTateApplication.EqualCharacteristicTransportedLevelTower
import LubinTate.FiniteLevel.StandardLocalField
import LocalClassFieldTheory.Concrete.LubinTateApplication.StandardNormIndex
import LocalClassFieldTheory.Concrete.LubinTateApplication.StandardSubgroupIndex
import LocalClassFieldTheory.Concrete.LubinTateApplication.StandardNormSubgroupExact
import LocalClassFieldTheory.Concrete.LubinTateApplication.TransportedNormSubgroupExact
import LocalClassFieldTheory.Concrete.LubinTateApplication.PadicMultiplicativeArtinComparison
import LocalClassFieldTheory.Concrete.LubinTateApplication.EqualCharacteristicTransportedRealFilteredComparison
import LocalClassFieldTheory.Concrete.LubinTateApplication.EqualCharacteristicUpperFiltration
import LocalClassFieldTheory.Concrete.LubinTateApplication.StandardFilteredArtinComparison
import LocalClassFieldTheory.Concrete.LubinTateApplication.EqualCharacteristicRealFilteredComparison
import LocalClassFieldTheory.Concrete.LubinTateApplication.EqualCharacteristicTransportedArtinComparison
import LocalClassFieldTheory.Concrete.LubinTateApplication.EqualCharacteristicTransportedFixedFieldComparison
import LocalClassFieldTheory.Concrete.LubinTateApplication.EqualCharacteristicTransportedUpperRestriction
import LocalClassFieldTheory.Concrete.LubinTateApplication.Filtered
import LocalClassFieldTheory.Concrete.LubinTateApplication.StandardArtinComparison
import LocalClassFieldTheory.Concrete.LubinTateApplication.StandardFixedFieldComparison

/-!
# Lubin--Tate application to local class field theory

This is the dependency boundary between reusable Lubin--Tate theory and its
local-class-field-theory application.  Finite local reciprocity identifies
the exact norm subgroup both for the canonical characteristic-independent
standard levels and for the transported Laurent-series model.  The lower
`LubinTate` public root and all modules below it remain independent of
`LocalClassFieldTheory.Concrete`.
-/
