import AlgebraicNumberTheory.Galois.AbsoluteAbelianization
import AlgebraicNumberTheory.Galois.CyclicPrimeDegreeSubextension
import AlgebraicNumberTheory.Galois.CyclicPrimeSubextension
import AlgebraicNumberTheory.Galois.FixedFieldLattice
import AlgebraicNumberTheory.Galois.InfiniteBaseChange
import AlgebraicNumberTheory.Galois.MaximalAbelianSubextension
import AlgebraicNumberTheory.Galois.NormalFieldRange

/-! # Galois subextensions and fixed-field constructions -/
