import LubinTate.EqualCharacteristic.CompletedLevel.ChangedCompletedLevel
import LubinTate.EqualCharacteristic.CompletedLevel.ChangedCompletedPrimitiveAction
import LubinTate.EqualCharacteristic.CompletedLevel.ChangedPolynomialEvaluation
import LubinTate.EqualCharacteristic.CompletedLevel.ChangedUniformizer
import LubinTate.EqualCharacteristic.CompletedLevel.ChangedUniformizerNormalization
import LubinTate.EqualCharacteristic.CompletedLevel.CompletedFrobeniusBaseEquiv
import LubinTate.EqualCharacteristic.CompletedLevel.CompletedFrobeniusContinuity
import LubinTate.EqualCharacteristic.CompletedLevel.CompletedFrobeniusFixedField
import LubinTate.EqualCharacteristic.CompletedLevel.CompletedFrobeniusFixedFieldAlgebra
import LubinTate.EqualCharacteristic.CompletedLevel.CompletedFrobeniusFixedFieldCoefficientDescent
import LubinTate.EqualCharacteristic.CompletedLevel.CompletedFrobeniusFixedFieldDegree
import LubinTate.EqualCharacteristic.CompletedLevel.CompletedFrobeniusFixedFieldGeneration
import LubinTate.EqualCharacteristic.CompletedLevel.CompletedFrobeniusFixedFieldPowerBasis
import LubinTate.EqualCharacteristic.CompletedLevel.CompletedFrobeniusFixedFieldPrimitive
import LubinTate.EqualCharacteristic.CompletedLevel.CompletedFrobeniusLift
import LubinTate.EqualCharacteristic.CompletedLevel.CompletedFrobeniusFixedNorm
import LubinTate.EqualCharacteristic.CompletedLevel.CompletedLevel
import LubinTate.EqualCharacteristic.CompletedLevel.CompletedPrimitiveAction
import LubinTate.EqualCharacteristic.CompletedLevel.CompletedPrimitiveIrreducible
import LubinTate.EqualCharacteristic.CompletedLevel.DirectBracketAtCompletedLevel
import LubinTate.EqualCharacteristic.CompletedLevel.DirectLubinTateBracket
import LubinTate.EqualCharacteristic.CompletedLevel.DirectLubinTateBracketRecursion
import LubinTate.EqualCharacteristic.CompletedLevel.DirectTargetLevelEmbedding
import LubinTate.EqualCharacteristic.CompletedLevel.DirectThetaAtCompletedLevel
import LubinTate.EqualCharacteristic.CompletedLevel.DirectThetaFirstIdentity
import LubinTate.EqualCharacteristic.CompletedLevel.DirectThetaFrobeniusFixed
import LubinTate.EqualCharacteristic.CompletedLevel.DirectThetaIteration
import LubinTate.EqualCharacteristic.CompletedLevel.DirectThetaSeries
import LubinTate.EqualCharacteristic.CompletedLevel.ThetaAtCompletedLevel
import LubinTate.EqualCharacteristic.CompletedLevel.ThetaLocalInverse

/-!
# Completed Lubin--Tate levels in equal characteristic

Public aggregate for completed level fields, Frobenius fixed fields, and
completed norm calculations.
-/
