import LubinTate.EqualCharacteristic.FiniteLevel.AmbientDivisionTorsion
import LubinTate.EqualCharacteristic.FiniteLevel.DivisionPolynomial
import LubinTate.EqualCharacteristic.FiniteLevel.FiniteParameters
import LubinTate.EqualCharacteristic.FiniteLevel.FreeRankOne
import LubinTate.EqualCharacteristic.FiniteLevel.LevelAbelian
import LubinTate.EqualCharacteristic.FiniteLevel.LevelAutomorphisms
import LubinTate.EqualCharacteristic.FiniteLevel.LevelField
import LubinTate.EqualCharacteristic.FiniteLevel.LevelFieldTower
import LubinTate.EqualCharacteristic.FiniteLevel.NormUniformizer
import LubinTate.EqualCharacteristic.FiniteLevel.PrimitiveAction
import LubinTate.EqualCharacteristic.FiniteLevel.PrimitiveIrreducible
import LubinTate.EqualCharacteristic.FiniteLevel.PrimitiveTorsion
import LubinTate.EqualCharacteristic.FiniteLevel.UnitQuotientGalois

/-!
# Finite Lubin--Tate levels in equal characteristic

Public aggregate for division torsion, finite level fields, and their Galois
and norm structure.
-/
