import ValuationTheory.Henselian.Factorization
import ValuationTheory.Henselian.Complete
import ValuationTheory.Henselian.IrreduciblePolynomialBounds
import ValuationTheory.Henselian.IrreduciblePolynomialLifting
import ValuationTheory.Henselian.MonicFactorization
import ValuationTheory.Henselian.NonmonicReduction
import ValuationTheory.Henselian.PrimitiveFactorization
import ValuationTheory.Henselian.PrimitiveReduction
import ValuationTheory.Henselian.UniqueAlgebraicExtensions
import ValuationTheory.Henselian.UniqueExtensionPrimitive
import ValuationTheory.Henselian.UniqueExtensionReduction
import ValuationTheory.Henselian.ValuationExtensionCriterion

/-!
# Arithmetic of Henselian valuations

Reusable factorization and uniqueness criteria for algebraic extensions of
Henselian valued fields.
-/
