import ValuationTheory.AbsoluteValue.Completeness
import ValuationTheory.AbsoluteValue.ExponentialValuation
import ValuationTheory.AbsoluteValue.PrincipalAdicCompleteness
import ValuationTheory.AbsoluteValue.ValuationSubring
import ValuationTheory.AbsoluteValue.AlgebraicExtension.FiniteNormExtension
import ValuationTheory.AbsoluteValue.AlgebraicExtension.NormFormula
import ValuationTheory.AbsoluteValue.AlgebraicExtension.NormFormulaAbsoluteValue
import ValuationTheory.AbsoluteValue.AlgebraicExtension.NormFormulaCoefficients
import ValuationTheory.AbsoluteValue.AlgebraicExtension.NormFormulaExtension
import ValuationTheory.AbsoluteValue.AlgebraicExtension.NormFormulaIntegralClosure
import ValuationTheory.AbsoluteValue.AlgebraicExtension.RamificationInvariants
import ValuationTheory.AbsoluteValue.AlgebraicExtension.UniqueExtensionCoefficients
import ValuationTheory.AbsoluteValue.AlgebraicExtension.UniqueValuationSubring

/-!
# Arithmetic extensions of absolute values

Norm formulas, valuation-ring comparisons, and ramification invariants for
algebraic extensions of complete valued fields.
-/
