import LocalClassFieldTheory.LubinTateApplication.NormIndex
import LocalClassFieldTheory.LubinTateApplication.NormSubgroup
import LocalClassFieldTheory.LubinTateApplication.LubinTateTransport
import LocalClassFieldTheory.LubinTateApplication.LaurentPrincipalUnitTransport
import LocalClassFieldTheory.LubinTateApplication.EqualCharacteristicTransportedUpperRamification
import LocalClassFieldTheory.LubinTateApplication.EqualCharacteristicTransportedLevelTower
import LocalClassFieldTheory.LubinTateApplication.StandardNormIndex
import LocalClassFieldTheory.LubinTateApplication.StandardSubgroupIndex
import LocalClassFieldTheory.LubinTateApplication.StandardNormSubgroupExact
import LocalClassFieldTheory.LubinTateApplication.TransportedNormSubgroupExact
import LocalClassFieldTheory.LubinTateApplication.PadicMultiplicativeArtinComparison
import LocalClassFieldTheory.LubinTateApplication.EqualCharacteristicTransportedRealFilteredComparison
import LocalClassFieldTheory.LubinTateApplication.EqualCharacteristicUpperFiltration
import LocalClassFieldTheory.LubinTateApplication.StandardFilteredArtinComparison
import LocalClassFieldTheory.LubinTateApplication.EqualCharacteristicRealFilteredComparison
import LocalClassFieldTheory.LubinTateApplication.EqualCharacteristicTransportedArtinComparison
import LocalClassFieldTheory.LubinTateApplication.EqualCharacteristicTransportedFixedFieldComparison
import LocalClassFieldTheory.LubinTateApplication.EqualCharacteristicTransportedUpperRestriction
import LocalClassFieldTheory.LubinTateApplication.StandardArtinComparison
import LocalClassFieldTheory.LubinTateApplication.StandardFixedFieldComparison

/-!
# Lubin--Tate application to local class field theory

This is the dependency boundary between reusable Lubin--Tate theory and its
local-class-field-theory application.  Finite local reciprocity identifies
the exact norm subgroup both for the canonical characteristic-independent
standard levels and for the transported Laurent-series model.  The lower
`LubinTate` public root and all modules below it remain independent of
`LocalClassFieldTheory`.
-/
