import ValuedFieldTheory.LocalField.Padic.ClosedAddSubgroup
import ValuedFieldTheory.LocalField.Padic.Cyclotomic.All
import ValuedFieldTheory.LocalField.Padic.NonarchimedeanLocalField
import ValuedFieldTheory.LocalField.Padic.PrincipalUnits
import ValuedFieldTheory.LocalField.Padic.UnitDecomposition

set_option autoImplicit false
