import GroupTheory.Transfer.RelativeAugmentation
import GroupTheory.Transfer.Witt
import GlobalClassFieldTheory.IdealClassFieldTheory.AbstractCapitulation
import GlobalClassFieldTheory.IdealClassFieldTheory.IdealArtinMap
import GlobalClassFieldTheory.IdealClassFieldTheory.IdealArtinQuotient
import GlobalClassFieldTheory.IdealClassFieldTheory.ArithmeticIdealArtin
import GlobalClassFieldTheory.IdealClassFieldTheory.IdealDecompositionLaw
import GlobalClassFieldTheory.IdealClassFieldTheory.ArithmeticIdealDecompositionLaw
import GlobalClassFieldTheory.IdealClassFieldTheory.IdealFrobenius
import GlobalClassFieldTheory.IdealClassFieldTheory.IdealNormArtinExactness
import GlobalClassFieldTheory.IdealClassFieldTheory.NormLimitationStatement
import GlobalClassFieldTheory.IdealClassFieldTheory.NormLimitationCore
import GlobalClassFieldTheory.IdealClassFieldTheory.NormLimitation
import GlobalClassFieldTheory.IdealClassFieldTheory.PrincipalIdealTheorem
import GlobalClassFieldTheory.IdealClassFieldTheory.PrincipalIdealTower
import GlobalClassFieldTheory.IdealClassFieldTheory.RationalAbstractExtensionToOrdinary
import GlobalClassFieldTheory.IdealClassFieldTheory.RationalFixedFieldBaseChange
import GlobalClassFieldTheory.IdealClassFieldTheory.RationalFiniteNormTransfer
import GlobalClassFieldTheory.IdealClassFieldTheory.SmallHilbertSplitting
import GlobalClassFieldTheory.IdealClassFieldTheory.SmallHilbertTowerConjugation
import GlobalClassFieldTheory.IdealClassFieldTheory.SmallHilbertTowerRealization
import GlobalClassFieldTheory.IdealClassFieldTheory.SmallHilbertTowerUnramified
import GlobalClassFieldTheory.IdealClassFieldTheory.PrincipalIdealTransfer
import GlobalClassFieldTheory.IdealClassFieldTheory.SmallHilbertPrincipalization

/-!
# Ideal class field theory

This public root exports ideal Artin maps and quotients, Frobenius classes,
splitting in the small Hilbert class field, the genuine idèle-extension
transfer square, and principalization of every integral and fractional ideal
in the selected small Hilbert class field.
-/
