import GlobalClassFieldTheory.Reciprocity.ComplexificationArtin
import GlobalClassFieldTheory.Reciprocity.CyclotomicTorsionFixedField
import GlobalClassFieldTheory.Reciprocity.CyclotomicZHatBaseChange
import GlobalClassFieldTheory.Reciprocity.FinitePlaceArtin
import GlobalClassFieldTheory.Reciprocity.FiniteIdeleArtin
import GlobalClassFieldTheory.Reciprocity.IdeleClassDirectLimitCore
import GlobalClassFieldTheory.Reciprocity.IdeleClassDirectLimitFiniteLevelCore
import GlobalClassFieldTheory.Reciprocity.IdeleClassDirectLimitFiniteLevel
import GlobalClassFieldTheory.Reciprocity.IdeleClassDirectLimitFixedPointDescentCore
import GlobalClassFieldTheory.Reciprocity.IdeleClassDirectLimitFixedPointDescent
import GlobalClassFieldTheory.Reciprocity.IdeleClassDirectLimitFixedPoints
import GlobalClassFieldTheory.Reciprocity.IdeleClassDirectLimitAbstractFixedField
import GlobalClassFieldTheory.Reciprocity.IdeleClassDirectLimitExtension
import GlobalClassFieldTheory.Reciprocity.IdeleClassDirectLimitExtensionAction
import GlobalClassFieldTheory.Reciprocity.IdeleClassDirectLimitExtensionNorm
import GlobalClassFieldTheory.Reciprocity.IdeleClassDirectLimitFiniteTowerNormCore
import GlobalClassFieldTheory.Reciprocity.IdeleClassDirectLimitFiniteTowerNormStatement
import GlobalClassFieldTheory.Reciprocity.IdeleClassDirectLimitFiniteTowerNormProof
import GlobalClassFieldTheory.Reciprocity.IdeleClassDirectLimitNormQuotient
import GlobalClassFieldTheory.Reciprocity.FiniteGaloisRealizationCore
import GlobalClassFieldTheory.Reciprocity.FiniteGaloisRealizationFinitePlace
import GlobalClassFieldTheory.Reciprocity.FiniteGaloisRealizationSubextension
import GlobalClassFieldTheory.Reciprocity.FiniteGaloisRealizationNormQuotient
import GlobalClassFieldTheory.Reciprocity.FiniteGaloisRealization
import GlobalClassFieldTheory.Reciprocity.IdeleClassNormTopology
import GlobalClassFieldTheory.Reciprocity.InfinitePlaceArtin
import GlobalClassFieldTheory.Reciprocity.GlobalArtin
import GlobalClassFieldTheory.Reciprocity.InfiniteGlobalArtin
import GlobalClassFieldTheory.Reciprocity.CyclotomicIdeleValue
import GlobalClassFieldTheory.Reciprocity.CyclotomicNormOneCorrection
import GlobalClassFieldTheory.Reciprocity.CyclotomicIdeleValueTopology
import GlobalClassFieldTheory.Reciprocity.CyclotomicPrincipalIdele
import GlobalClassFieldTheory.Reciprocity.LocalGlobalArtinCompatibility
import GlobalClassFieldTheory.Reciprocity.NormQuotient
import GlobalClassFieldTheory.Reciprocity.FiniteLocalFamily
import GlobalClassFieldTheory.Reciprocity.GlobalArtinFiniteSupportApproximation
import GlobalClassFieldTheory.Reciprocity.GlobalHilbertSymbol
import GlobalClassFieldTheory.Reciprocity.OnePlaceNormKernel
import GlobalClassFieldTheory.Reciprocity.ProductFormula
import GlobalClassFieldTheory.Reciprocity.RationalCyclotomicCharacterRigidity
import GlobalClassFieldTheory.Reciprocity.RationalCyclotomicFinitePlace
import GlobalClassFieldTheory.Reciprocity.RationalCyclotomicLocalization
import GlobalClassFieldTheory.Reciprocity.RationalCyclotomicZHatRigidity
import GlobalClassFieldTheory.Reciprocity.RationalPrimeFactorization
import GlobalClassFieldTheory.Reciprocity.RationalPrincipalLocalUnit
import GlobalClassFieldTheory.Reciprocity.RationalCyclotomicFinitePlaceArtin
import GlobalClassFieldTheory.Reciprocity.RationalCyclotomicPrincipalAwayProduct
import GlobalClassFieldTheory.Reciprocity.RationalCyclotomicPrincipalPrimeFactor
import GlobalClassFieldTheory.Reciprocity.FinitePlaceCyclotomicFrobeniusLift
import GlobalClassFieldTheory.Reciprocity.RationalCyclotomicPrincipalProduct
import GlobalClassFieldTheory.Reciprocity.CyclotomicIdeleClassValuation
import GlobalClassFieldTheory.Reciprocity.CyclotomicAbstractFixedFieldArtin
import GlobalClassFieldTheory.Reciprocity.GlobalNormResidue
import GlobalClassFieldTheory.Reciprocity.AbstractFixedFieldGlobalNormResidue
import GlobalClassFieldTheory.Reciprocity.CyclotomicUnramifiedRestriction
import GlobalClassFieldTheory.Reciprocity.CyclotomicUnramifiedGeometricRestriction
import GlobalClassFieldTheory.Reciprocity.GlobalNormResidueAbelianization
import GlobalClassFieldTheory.Reciprocity.GlobalNormResidueNaturality
import GlobalClassFieldTheory.Reciprocity.GlobalNormResidueAbelianizationNaturality
import GlobalClassFieldTheory.Reciprocity.IntermediateNormAbelianization
import GlobalClassFieldTheory.Reciprocity.CyclotomicUnramifiedLocalGlobalCompatibility
import GlobalClassFieldTheory.Reciprocity.InfiniteLocalGlobalArtinCompatibility
import GlobalClassFieldTheory.Reciprocity.RationalCyclotomicRayNorm
import GlobalClassFieldTheory.Reciprocity.TopologicalGlobalNormResidue
import GlobalClassFieldTheory.Reciprocity.GlobalArtinCompatibility
import GlobalClassFieldTheory.Reciprocity.InfiniteGlobalArtinDescent
import GlobalClassFieldTheory.Reciprocity.InfiniteGlobalArtinSurjectivity
import GlobalClassFieldTheory.Reciprocity.MaximalAbelianGlobalArtin
import GlobalClassFieldTheory.Reciprocity.MaximalAbelianKernel
import GlobalClassFieldTheory.Reciprocity.TopologicalGlobalNormResidueAbelianization
import GlobalClassFieldTheory.Reciprocity.ArithmeticNormalization
import GlobalClassFieldTheory.Reciprocity.RationalCyclotomicArithmeticProduct

/-!
# Global reciprocity

This public root exports global Artin maps, cyclotomic comparisons, local norm
kernels, the principal-idèle product formula, the concrete cyclotomic
idèle-class valuation, local--global compatibility, and the descended global
norm-residue homomorphism with its actual norm-range kernel.
-/
