import LubinTate.Padic.ChangedUniformizerCoefficient
import LubinTate.Padic.ChangedUniformizerIntertwiner
import LubinTate.Padic.CompletedChangedStandardCompositum
import LubinTate.Padic.CompletedChangedStandardFixedField
import LubinTate.Padic.CompletedChangedStandardFrobenius
import LubinTate.Padic.CompletedChangedStandardResidue
import LubinTate.Padic.CompletedChangedStandardUnramified
import LubinTate.Padic.CompletedChangedUniformizerFixedField
import LubinTate.Padic.CompletedChangedUniformizerPrimitive
import LubinTate.Padic.CompletedChangedUniformizerThetaFixed
import LubinTate.Padic.CompletedFrobeniusEvaluation
import LubinTate.Padic.CompletedFrobeniusLift
import LubinTate.Padic.CompletedLevel
import LubinTate.Padic.CompletedPrimitiveAction
import LubinTate.Padic.CompletedPrimitiveIrreducible
import LubinTate.Padic.CompletedPrimitiveUniformizer
import LubinTate.Padic.CompletedResidueFrobenius
import LubinTate.Padic.CompletedStandardLevelTransport
import LubinTate.Padic.CompletedUnramifiedField
import LubinTate.Padic.CompletedUnramifiedFrobeniusFixed
import LubinTate.Padic.MultiplicativeEvaluation
import LubinTate.Padic.MultiplicativeIntertwiner
import LubinTate.Padic.MultiplicativeSeries

/-!
# P-adic Lubin--Tate theory

Aggregate for the multiplicative Lubin--Tate series and its completed-level,
Frobenius, residue, fixed-field, and changed-uniformizer constructions.
-/
