import LocalFieldTheory.DiscreteValuationField.Basic
import LocalFieldTheory.DiscreteValuationField.EqualCharacteristicLaurent
import LocalFieldTheory.DiscreteValuationField.MixedCharacteristicQp
import LocalFieldTheory.DiscreteValuationField.PadicField
import LocalFieldTheory.DiscreteValuationField.FiniteCoefficientLaurent
import LocalFieldTheory.DiscreteValuationField.FieldNormBase
import LocalFieldTheory.DiscreteValuationField.FieldUnitDecomposition
import LocalFieldTheory.DiscreteValuationField.RamificationIdeal
import LocalFieldTheory.DiscreteValuationField.RamificationInvariants
import LocalFieldTheory.DiscreteValuationField.ValuationSubringUnits
import LocalFieldTheory.DiscreteValuationField.WithZeroValuationTopology
import LocalFieldTheory.DiscreteValuationField.FieldNorm
import LocalFieldTheory.DiscreteValuationField.FieldNormEquiv
import LocalFieldTheory.DiscreteValuationField.PolynomialRootProximity
import LocalFieldTheory.DiscreteValuationField.RamificationAddVal
import LocalFieldTheory.DiscreteValuationField.NormFiltration
import LocalFieldTheory.DiscreteValuationField.PrincipalUnits
import LocalFieldTheory.DiscreteValuationField.PrincipalUnitPadicAction
import LocalFieldTheory.DiscreteValuationField.PrincipalUnitInverseLimitSurjectivity
import LocalFieldTheory.DiscreteValuationField.PadicLinearOfContinuous
import LocalFieldTheory.DiscreteValuationField.FieldUnitFactors
import LocalFieldTheory.DiscreteValuationField.PadicModuleStructure
import LocalFieldTheory.DiscreteValuationField.MixedCharacteristicStructure
import LocalFieldTheory.DiscreteValuationField.Norm
import LocalFieldTheory.DiscreteValuationField.IwasawaIndexing
import LocalFieldTheory.DiscreteValuationField.IwasawaPrincipalUnits
import LocalFieldTheory.DiscreteValuationField.FieldUnitStructure
import LocalFieldTheory.DiscreteValuationField.PowerIndex
import LocalFieldTheory.DiscreteValuationField.PadicPowerIndex
import LocalFieldTheory.DiscreteValuationField.FieldUnitPowerIndexFormulas
import LocalFieldTheory.DiscreteValuationField.Units
import LocalFieldTheory.DiscreteValuationField.ValueGroup
import LocalFieldTheory.DiscreteValuationField.PadicValuationComparison

/-!
# Local-field algebraic infrastructure

Focused aggregate for valued-field basics, ramification invariants, norms, and unit filtrations.
-/
