import GlobalClassFieldTheory.ClassFieldAxiom.SUnitKummerPrimeSelection.FinitePlaceDecomposition
import GlobalClassFieldTheory.ClassFieldAxiom.SUnitKummerPrimeSelection.RestrictionKernel
import GlobalClassFieldTheory.ClassFieldAxiom.SUnitKummerPrimeSelection.BasePlaceSelection
import GlobalClassFieldTheory.ClassFieldAxiom.SUnitKummerPrimeSelection.CoordinatePlaces
import GlobalClassFieldTheory.ClassFieldAxiom.SUnitKummerPrimeSelection.PrimeSet
import GlobalClassFieldTheory.ClassFieldAxiom.SUnitKummerPrimeSelection.DecompositionFields
import GlobalClassFieldTheory.ClassFieldAxiom.SUnitKummerPrimeSelection.Conclusion

/-!
# S-unit Kummer prime selection

This aggregate module exposes the restriction-kernel construction, prime
selection, decomposition-field identifications, and the final local-power
kernel theorem.
-/
