import GaloisCohomology.Kummer.Concrete.Cyclotomic.All
import GaloisCohomology.Kummer.Concrete.CyclotomicField
import GaloisCohomology.Kummer.Concrete.ExtensionRoundTrip
import GaloisCohomology.Kummer.Concrete.FiniteCharacterEquiv
import GaloisCohomology.Kummer.Concrete.FiniteDualSeparation
import GaloisCohomology.Kummer.Concrete.FiniteGeneration
import GaloisCohomology.Kummer.Concrete.FiniteSupport
import GaloisCohomology.Kummer.Concrete.GaloisCohomology
import GaloisCohomology.Kummer.Concrete.InfiniteContinuity
import GaloisCohomology.Kummer.Concrete.InfiniteGeneration
import GaloisCohomology.Kummer.Concrete.InfiniteInverse
import GaloisCohomology.Kummer.Concrete.KummerCorrespondenceFormula
import GaloisCohomology.Kummer.Concrete.LocalMaximalKummerExtension
import GaloisCohomology.Kummer.Concrete.LocalUnitKummerUnramified
import GaloisCohomology.Kummer.Concrete.MaximalKummerSubgroup
import GaloisCohomology.Kummer.Concrete.RadicalExtension
import GaloisCohomology.Kummer.Concrete.RadicalQuotient
import GaloisCohomology.Kummer.Concrete.RestrictedFinite
import GaloisCohomology.Kummer.Concrete.RootCharacters
import GaloisCohomology.Kummer.Concrete.SUnitPreparation.All
import GaloisCohomology.Kummer.Concrete.SimpleExtension
import GaloisCohomology.Kummer.Concrete.SimpleExtensionNorm

set_option autoImplicit false
