import GlobalClassFieldTheory.IdealClassFieldTheory.RationalFiniteNormTransfer.FieldSpine
import GlobalClassFieldTheory.IdealClassFieldTheory.RationalFiniteNormTransfer.Representatives
import GlobalClassFieldTheory.IdealClassFieldTheory.RationalFiniteNormTransfer.Compatibility
import GlobalClassFieldTheory.IdealClassFieldTheory.RationalFiniteNormTransfer.Quotient
import GlobalClassFieldTheory.IdealClassFieldTheory.RationalFiniteNormTransfer.MembershipTypes
import GlobalClassFieldTheory.IdealClassFieldTheory.RationalFiniteNormTransfer.ZeroTransport
import GlobalClassFieldTheory.IdealClassFieldTheory.RationalFiniteNormTransfer.FiniteNormClass

/-!
# Rational finite-norm transport

This compatibility facade exports the fixed-field instance spine and the
independently compiled representative, quotient, compatibility, membership,
zero-transport, and final finite-norm-class leaves.
-/
