import LocalClassFieldTheory.Concrete.LubinTateApplication.EqualCharacteristicUpperFiltration
import LocalClassFieldTheory.Concrete.LubinTateApplication.StandardArtinComparison
import LocalClassFieldTheory.Concrete.LubinTateApplication.StandardFilteredArtinComparison
import LocalClassFieldTheory.Concrete.LubinTateApplication.StandardFixedFieldComparison
import LocalClassFieldTheory.Concrete.LubinTateApplication.EqualCharacteristicRealFilteredComparison
import LocalClassFieldTheory.Concrete.LubinTateApplication.EqualCharacteristicTransportedUpperRestriction
import LocalClassFieldTheory.Concrete.LubinTateApplication.EqualCharacteristicTransportedArtinComparison
import LocalClassFieldTheory.Concrete.LubinTateApplication.EqualCharacteristicTransportedRealFilteredComparison
import LocalClassFieldTheory.Concrete.LubinTateApplication.EqualCharacteristicTransportedFixedFieldComparison

/-!
# Lubin--Tate filtered-reciprocity comparisons

Public aggregate for the Artin and upper-ramification comparisons attached
to standard and transported Lubin--Tate levels.  It is kept separate from
the core norm-subgroup application facade so finite local existence may use
that lower layer without a dependency cycle.
-/
