import LocalClassFieldTheory.Finite.LocalReciprocity.Core
import LocalClassFieldTheory.Finite.LocalReciprocity.IntermediateFieldNormResidueNaturality
import LocalClassFieldTheory.Finite.LocalReciprocity.AbsoluteUnitsFixedField
import LocalClassFieldTheory.Finite.LocalReciprocity.AbstractFixedFieldNorm
import LocalClassFieldTheory.Finite.LocalReciprocity.AbstractFixedFieldUnits
import LocalClassFieldTheory.Finite.LocalReciprocity.FixedFieldRelativeNorm
import LocalClassFieldTheory.Finite.LocalReciprocity.FixedFieldNormResidueNaturality
import LocalClassFieldTheory.Finite.LocalReciprocity.FixedFieldContinuousNaturality
import LocalClassFieldTheory.Finite.LocalReciprocity.FixedFieldIntrinsicReciprocity
import LocalClassFieldTheory.Finite.LocalReciprocity.ConcreteReciprocityCanonical
import LocalClassFieldTheory.Finite.LocalReciprocity.ConcreteReciprocityTransport
import LocalClassFieldTheory.Finite.LocalReciprocity.ConjugationNaturality
import LocalClassFieldTheory.Finite.LocalReciprocity.FiniteAbstractFixedField
import LocalClassFieldTheory.Finite.LocalReciprocity.FiniteExtensionClassFieldAxiom
import LocalClassFieldTheory.Finite.LocalReciprocity.FiniteGaloisRealization
import LocalClassFieldTheory.Finite.LocalReciprocity.FiniteResidueFinrankTransfer
import LocalClassFieldTheory.Finite.LocalReciprocity.FiniteResidueFrobenius
import LocalClassFieldTheory.Finite.LocalReciprocity.FiniteResidueValuationComparison
import LocalClassFieldTheory.Finite.LocalReciprocity.FiniteSubgroupResidueDegree
import LocalClassFieldTheory.Finite.LocalReciprocity.GaloisExtensionQuotient
import LocalClassFieldTheory.Finite.LocalReciprocity.HenselianValuationBase
import LocalClassFieldTheory.Finite.LocalReciprocity.LocalClassFieldAxiom
import LocalClassFieldTheory.Finite.LocalReciprocity.LocalHenselianValuation
import LocalClassFieldTheory.Finite.LocalReciprocity.LocalResidueDatum
import LocalClassFieldTheory.Finite.LocalReciprocity.ResidueAbsoluteDegree
import LocalClassFieldTheory.Finite.LocalReciprocity.ResidueAbsoluteFrobenius
import LocalClassFieldTheory.Finite.LocalReciprocity.ResidueActionIndex
import LocalClassFieldTheory.Finite.LocalReciprocity.ResidueAlgebraicClosureDegree
import LocalClassFieldTheory.Finite.LocalReciprocity.ResidueAlgebraicallyClosed
import LocalClassFieldTheory.Finite.LocalReciprocity.ResidueDatum
import LocalClassFieldTheory.Finite.LocalReciprocity.SeparableFixedFieldNorm
import LocalClassFieldTheory.Finite.LocalReciprocity.SeparableNormValuation
import LocalClassFieldTheory.Finite.LocalReciprocity.SeparableUnitsNorm
import LocalClassFieldTheory.Finite.LocalReciprocity.TateTransport
import LocalClassFieldTheory.Finite.LocalReciprocity.Main
import LocalClassFieldTheory.Finite.LocalReciprocity.TopologicalReciprocity
import LocalClassFieldTheory.Finite.LocalReciprocity.NormResidue
import LocalClassFieldTheory.Finite.LocalReciprocity.NormResidueNaturality
import LocalClassFieldTheory.Finite.LocalReciprocity.GeneralTowerNaturality
import LocalClassFieldTheory.Finite.LocalReciprocity.ConcreteReciprocityPrimeNorm
import LocalClassFieldTheory.Finite.LocalReciprocity.UnramifiedComparison
import LocalClassFieldTheory.Finite.LocalReciprocity.UnramifiedNormComparison
import LocalClassFieldTheory.Finite.LocalReciprocity.UnramifiedReciprocity
import LocalClassFieldTheory.Finite.LocalReciprocity.UnramifiedNormalization
import LocalClassFieldTheory.Finite.LocalReciprocity.CompositumRestriction
import LocalClassFieldTheory.Finite.LocalReciprocity.Filtered
import LocalClassFieldTheory.Finite.LocalReciprocity.SemilinearNaturality
import LocalClassFieldTheory.Finite.LocalReciprocity.SeparableNormProduct
import LocalClassFieldTheory.Finite.LocalReciprocity.IntrinsicAbsoluteData
import LocalClassFieldTheory.Finite.LocalReciprocity.FixedFieldLocalData

/-!
# Finite local reciprocity

Exhaustive aggregate for the finite-level reciprocity equivalence, the continuous local Artin map,
its norm kernel and surjectivity, and the local class-formation construction beneath them.
-/
