import Mathlib.SetTheory.Cardinal.Finite
import Mathlib.FieldTheory.KummerExtension

/-!
# Cyclic Kummer extensions

A cyclic Galois extension whose Galois group has exponent dividing `n` is
generated by a single element whose `n`-th power lies in the base field,
provided the base field contains a primitive `n`-th root of unity.
-/

namespace KummerTheory

open IntermediateField

variable {K L : Type*} [Field K] [Field L] [Algebra K L]

private theorem finiteDimensionalOfCyclicGaloisExponent
    [IsGalois K L] [IsCyclic Gal(L/K)]
    (n : ℕ+) (hexponent : ∀ σ : Gal(L/K), σ ^ (n : ℕ) = 1) :
    FiniteDimensional K L := by
  obtain ⟨σ, hσ⟩ := (inferInstance : IsCyclic Gal(L/K))
  have hσ_finite : IsOfFinOrder σ :=
    isOfFinOrder_iff_pow_eq_one.2 ⟨(n : ℕ), n.pos, hexponent σ⟩
  letI : Fintype (Subgroup.zpowers σ) :=
    Fintype.ofEquiv (Fin (orderOf σ)) (finEquivZPowers hσ_finite)
  letI : Finite Gal(L/K) := Finite.of_surjective
    (fun x : Subgroup.zpowers σ => (x : Gal(L/K))) (by
      intro τ
      exact ⟨⟨τ, hσ τ⟩, rfl⟩)
  exact IsGalois.finiteDimensional_of_finite K L

private theorem finrankDvdOfCyclicGaloisExponent
    [IsGalois K L] [IsCyclic Gal(L/K)]
    (n : ℕ+) (hexponent : ∀ σ : Gal(L/K), σ ^ (n : ℕ) = 1) :
    Module.finrank K L ∣ (n : ℕ) := by
  letI : FiniteDimensional K L :=
    finiteDimensionalOfCyclicGaloisExponent n hexponent
  obtain ⟨σ, hσ⟩ := (inferInstance : IsCyclic Gal(L/K))
  have horder : orderOf σ = Nat.card Gal(L/K) :=
    orderOf_eq_card_of_forall_mem_zpowers hσ
  have horder_dvd : orderOf σ ∣ (n : ℕ) :=
    orderOf_dvd_of_pow_eq_one (hexponent σ)
  have hcard : Nat.card Gal(L/K) = Module.finrank K L := by
    rw [IsGalois.card_aut_eq_finrank]
  rw [horder, hcard] at horder_dvd
  exact horder_dvd

/-- A cyclic Galois extension of exponent dividing `n` is generated by one
nonzero radical when the base field contains a primitive `n`-th root of
unity. -/
theorem exists_single_radical_generator_of_cyclic_galois_exponent
    [IsGalois K L] [IsCyclic Gal(L/K)]
    (n : ℕ+) (hμ : (primitiveRoots (n : ℕ) K).Nonempty)
    (hexponent : ∀ σ : Gal(L/K), σ ^ (n : ℕ) = 1) :
    ∃ α : L, α ≠ 0 ∧
      α ^ (n : ℕ) ∈ Set.range (algebraMap K L) ∧ K⟮α⟯ = ⊤ := by
  letI : FiniteDimensional K L :=
    finiteDimensionalOfCyclicGaloisExponent n hexponent
  let d := Module.finrank K L
  have hd_pos : 0 < d := Module.finrank_pos
  have hd_dvd_n : d ∣ (n : ℕ) :=
    finrankDvdOfCyclicGaloisExponent (K := K) (L := L) n hexponent
  obtain ⟨ζ, hζ⟩ := hμ
  have hζ_primitive : IsPrimitiveRoot ζ (n : ℕ) :=
    (mem_primitiveRoots n.pos).1 hζ
  have hn_factor : (n : ℕ) = ((n : ℕ) / d) * d :=
    (Nat.div_mul_cancel hd_dvd_n).symm
  have hζd : IsPrimitiveRoot (ζ ^ ((n : ℕ) / d)) d :=
    hζ_primitive.pow n.pos hn_factor
  have hμd : (primitiveRoots d K).Nonempty :=
    ⟨ζ ^ ((n : ℕ) / d), (mem_primitiveRoots hd_pos).2 hζd⟩
  obtain ⟨α, hαd, hαgen⟩ :=
    exists_root_adjoin_eq_top_of_isCyclic K L hμd
  by_cases hαzero : α = 0
  · refine ⟨1, one_ne_zero, ⟨1, by simp⟩, ?_⟩
    have hbot : (⊥ : IntermediateField K L) = ⊤ := by
      simpa [hαzero] using hαgen
    simpa using hbot
  obtain ⟨a, ha⟩ := hαd
  have hn_factor' : (n : ℕ) = d * ((n : ℕ) / d) := by
    rw [Nat.mul_comm]
    exact hn_factor
  refine ⟨α, hαzero, ⟨a ^ ((n : ℕ) / d), ?_⟩, hαgen⟩
  symm
  calc
    α ^ (n : ℕ) = α ^ (d * ((n : ℕ) / d)) :=
      congrArg (fun m : ℕ => α ^ m) hn_factor'
    _ = (α ^ d) ^ ((n : ℕ) / d) := pow_mul α d ((n : ℕ) / d)
    _ = (algebraMap K L a) ^ ((n : ℕ) / d) := by rw [← ha]
    _ = algebraMap K L (a ^ ((n : ℕ) / d)) := by rw [map_pow]

end KummerTheory
