import ValuedFieldTheory.LocalField.Padic.Cyclotomic.TotallyRamified.EisensteinPolynomial
import ValuedFieldTheory.LocalField.Padic.Cyclotomic.TotallyRamified.EisensteinRelation
import ValuedFieldTheory.LocalField.Padic.Cyclotomic.TotallyRamified.Existence
import ValuedFieldTheory.LocalField.Padic.Cyclotomic.TotallyRamified.IntegralClosure
import ValuedFieldTheory.LocalField.Padic.Cyclotomic.TotallyRamified.IntegralTranslate
import ValuedFieldTheory.LocalField.Padic.Cyclotomic.TotallyRamified.PrimeElement
import ValuedFieldTheory.LocalField.Padic.Cyclotomic.TotallyRamified.RamificationIndex
import ValuedFieldTheory.LocalField.Padic.Cyclotomic.TotallyRamified.ValuationRingEquiv

set_option autoImplicit false
