import ValuedFieldTheory.Ramification.LocalField.BaseChange
import ValuedFieldTheory.Ramification.LocalField.Core
import ValuedFieldTheory.Ramification.LocalField.Unramified

set_option autoImplicit false
