import ClassFieldTheory.Theorems.HasseArf.HasseArf
import ClassFieldTheory.Theorems.HasseArf.HerbrandFunctionAtLowerIndexStrictMono
import ClassFieldTheory.Theorems.HasseArf.HerbrandFunctionAtLowerIndexDifference
import ClassFieldTheory.Theorems.HasseArf.HerbrandFunctionAtLowerIndexNatOfJump
import ClassFieldTheory.Theorems.HasseArf.HerbrandFunctionCanonical
import ClassFieldTheory.Theorems.HasseArf.HerbrandFunctionInverseHerbrandFunction
import ClassFieldTheory.Theorems.HasseArf.HerbrandFunctionNat
import ClassFieldTheory.Theorems.HasseArf.InverseHerbrandFunctionHerbrandFunction
import ClassFieldTheory.Theorems.HasseArf.IsUpperRamificationJumpInt
import ClassFieldTheory.Theorems.HasseArf.LowerRamificationGroupAntitone
import ClassFieldTheory.Theorems.HasseArf.LowerRamificationGroupEventuallyBot
import ClassFieldTheory.Theorems.HasseArf.LowerRamificationGroupNormal
import ClassFieldTheory.Theorems.HasseArf.LowerRamificationGroupZeroEqInertia
import ClassFieldTheory.Theorems.HasseArf.RealLowerRamificationGroupCanonical
import ClassFieldTheory.Theorems.HasseArf.RealLowerRamificationGroupNat
import ClassFieldTheory.Theorems.HasseArf.RealLowerRamificationGroupNormal
import ClassFieldTheory.Theorems.HasseArf.RealAndUpperRamificationGroupNormal
import ClassFieldTheory.Theorems.HasseArf.UpperRamificationGroupAntitone
import ClassFieldTheory.Theorems.HasseArf.UpperRamificationGroupCanonical
import ClassFieldTheory.Theorems.HasseArf.UpperRamificationGroupAfter
import ClassFieldTheory.Theorems.HasseArf.UpperRamificationGroupEventuallyBot

set_option autoImplicit false

/-! Public Hasse--Arf theorem and basic lower-filtration identities. -/
