import GaloisCohomology.ProfiniteIntegers.CyclotomicTorsionQuotient
import GaloisCohomology.ProfiniteIntegers.ProfiniteInteger
import GaloisCohomology.ProfiniteIntegers.ProfiniteIntegerCore
import GaloisCohomology.ProfiniteIntegers.ProfiniteIntegerPrimeProduct
import GaloisCohomology.ProfiniteIntegers.ProfiniteIntegerUnits
import GaloisCohomology.ProfiniteIntegers.TopologicalGeneration

set_option autoImplicit false
